version: '3.8'

services:
  app:
    build: .
    container_name: gerenciador-projeto
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: gerenciador_projeto
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cs45ii52ng1s739eisgg-a.oregon-postgres.render.com:5432/gerenciador_projeto
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: iZXI2FzQyEJGEdFbRU8FmGs431fBs4Wr
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: gerenciador_projeto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: